# Generated by Django 5.1 on 2024-08-30 14:35

from django.db import (
    migrations,
    models,
)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Назва компанії"),
                ),
            ],
            options={
                "verbose_name": "Тип компанії",
                "verbose_name_plural": "Типи компаній",
            },
        ),
    ]
